name = "InverseGraphicsRegistry"
uuid = "7d83f869-d38f-4bdf-bfd8-976e498b1c96"
repo = "git@github.com:probcomp/InverseGraphicsRegistry.git"
description = "InverseGraphicsRegistry"

[packages]
3bb1c1c2-7757-4fec-887f-d291af7e88d4 = { name = "MeshCatViz", path = "M/MeshCatViz" }
d1e26eb4-c061-4a47-b8d4-4152ce573b03 = { name = "GLRenderer", path = "G/GLRenderer" }
