name = "InverseGraphicsRegistry"
uuid = "7d83f869-d38f-4bdf-bfd8-976e498b1c96"
repo = "git@github.com:probcomp/InverseGraphicsRegistry.git"
description = "InverseGraphicsRegistry"

[packages]
38ed6c62-afb3-4a05-8af9-4104512be020 = { name = "GenArrow", path = "G/GenArrow" }
3bb1c1c2-7757-4fec-887f-d291af7e88d4 = { name = "MeshCatViz", path = "M/MeshCatViz" }
3f517155-95b4-4010-b517-e038c017d66c = { name = "Plinf", path = "P/Plinf" }
4b85a743-8232-4f48-902e-cd249a333b61 = { name = "InverseGraphics", path = "I/InverseGraphics" }
5fbb99ef-bc26-44e9-8a46-eed37f757c39 = { name = "Open3DVisualizer", path = "O/Open3DVisualizer" }
85d806fb-b5ca-4d38-9c94-d1c1a6747d55 = { name = "GenDirectionalStats", path = "G/GenDirectionalStats" }
888bd7f2-f8c6-44ef-b90f-8999fb25fa02 = { name = "MiniGSG", path = "M/MiniGSG" }
d1e26eb4-c061-4a47-b8d4-4152ce573b03 = { name = "GLRenderer", path = "G/GLRenderer" }
